---

- hosts: master
  vars_files:
    - inventory/cobra-rocky9/group_vars/vault.yaml
  roles:
    - role: k8s/secrets
      become: true

- hosts: localhost
  vars_files:
    - inventory/cobra-rocky9/group_vars/vault.yaml
  roles:
    - role: k8s/charts
      become: false