- name: Create namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
  loop: "{{ secrets }}"
  no_log: true

- name: Create secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
      stringData: "{{ secrets[0].stringData }}"
  loop: "{{ secrets }}"
  no_log: true